{
 "title": "Schema Validation",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "All tables",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count by(status)(tables_total)" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(\n  info)\n(tables_total{status=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count by(\n  name, status)\n(tables_total{status=\"Passed\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "count by(\n  name, info, status)\n(tables_total{status=\"Failed\"})"
    }
   ]
  }
 ]
}